add_newline     = true
command_timeout = 1000

format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$kubernetes\
$aws\
$all
"""

[git_status]
style = "bold #ff5555"

[hostname]
style = "bold #ff5555"

[aws]
disabled = false
style  = "bold #FFAC31"
format = "on[ â˜ï¸  $profile ]($style)"

[battery]
charging_symbol    = "âš¡ï¸ "
discharging_symbol = "â˜ ï¸  "
full_symbol        = "ğŸ”‹ "
unknown_symbol     = "ğŸ¤¨ "

[[battery.display]]
threshold = 15
style     = "bold red"

[[battery.display]]
threshold = 30
style     = "bold yellow"

[character]
success_symbol = "[âœ](bold green)" 
error_symbol   = "[âœ](bold red)"

[cmd_duration]
min_time = 5000
style = "bold #f1fa8c"

[directory]
truncation_length = 6
truncate_to_repo  = true
style             = "bold #50fa7b"

[docker_context]
format = "via[ ğŸ³ $context ](bold blue)"

[git_branch]
style = "bold #ff79c6"
format = "â€¢[ $symbol$branch ]($style)"

[helm]
disabled = false
format = "via[ âˆ$version ](bold white)"

[kubernetes]
disabled = false
format = 'on[ â˜¸ï¸  $context \($namespace\) ](bold cyan)'

[nim]
format = "via[ ğŸ‘‘ $version ]($style)"

[python]
symbol             = "ğŸ "
style              = "green"
python_binary      = ["python3"]
pyenv_version_name = true

[username]
disabled = true

[shell]
disabled = true

[terraform]
format = 'via[ â¬¢ $version \($workspace\) ]($style)'
